### ISSUE TITLE
Unexpected issue / crash

### ISSUE THREAD

**Issue by gmaclennan** [datproject/dat-desktop#275] opened 2017-02-24 02:18 UTC
Managed to break things pretty fast (the only thing I did with the app):

1. Create a new DAT from a folder (containing 4 small PDFs)
2. Remove the DAT by clicking the trash can
3. Create a new DAT again from the same folder

I tried to replicate after deleting `~/Library/Application Support/Dat` but now it works.

Also: When I got the fatal crash error I selected "delete database and contents" or whatever option is on the left that seemed like delete everything, but after doing that it seemed like the database was not wiped, since the folder that I had added (which caused the crash) was still there.

**Comment by yoshuawuyts** [comment] 2017-02-27 11:58
Hey there 👋 - thanks for reporting; reports like these are super helpful! I think there might be two causes for the issue you're seeing:

First off it seems the UI might not always match up with what the actual state is. Like in https://github.com/datproject/dat-desktop/issues/259 the UI doesn't reflect the app is currently being removed, causing it to error out on retries. I think this would be helpful.

Second I suspect we might be making some wrong assumptions with recreating Dats. In the past we've encountered `leveldb` lock files not being cleaned up when deleting, which caused issues when recreating. It appears there might be a subtle bug of the same kind causing this error. 

One quick question:
> I tried to replicate after deleting ~/Library/Application Support/Dat but now it works.

Does that mean that you tried recreating the issue (following all 3 steps, on a fresh directory) and you couldn't reproduce? Knowing if that was the case would be very helpful. Thanks again!

**Comment by gmaclennan** [comment] 2017-02-27 20:29
> Does that mean that you tried recreating the issue (following all 3 steps, on a fresh directory) and you couldn't reproduce? Knowing if that was the case would be very helpful. Thanks again!

Yes, I tried to recreate the issue but I could not. I know un-recreatable bugs are hard, sorry!

**Comment by juliangruber** [comment] 2017-05-15 11:31
we now upgraded our internal "dat" stack to the SLEEP version, by which a great many things changed. I tried to reproduce but I couldn't. Let's close for and hope this is fixed in the next release :)

**Closed by juliangruber** 2017-05-15 11:31 UTC
Labels: Priority: High, Status: Available, Type: Bug
