### ISSUE TITLE
deleted dat is added back

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#403] opened 2017-05-27 13:51 UTC
@Kriesse:

> If I delete a dat from the desktop app, and also delete the folder via Finder, then refresh the app, the deleted dat comes back. And the folder is created as well.

**Comment by juliangruber** [comment] 2017-05-29 12:35
I can't reproduce, maybe that's part of an outdated dependency. Can you try to reproduce with a fresh set of dependencies?

**Comment by Kriesse** [comment] 2017-05-29 13:24
@juliangruber Yup, can't reproduce it anymore either, closing!

**Closed by Kriesse** 2017-05-29 13:24 UTC
Labels: Priority: High, Status: Available, Type: Bug
