### ISSUE TITLE
Creating a new dat and sharing is broken

### ISSUE THREAD

**Issue by clkao** [datproject/dat-desktop#87] opened 2016-11-21 09:35 UTC
1. Create a new dat (choose some directory), obtain dat link
2. Use dat cli to clone that link. it hangs without knowing how many files are in the archive
3. If you reload the desktop app, the running dat cli might suddenly know the number of files, but still unable to download.

Interestingly if the desktop is re-sharing something (via dat-js download api), it can upload  to other client fine:
1. Create a new dat with dat cli A
2. Open desktop with that dat link
3. Close cli A
4. in cli B, clone the above link, and the files are streamed from the desktop app.

**Comment by karissa** [comment] 2016-11-21 21:41
I was able to reproduce this error. It seems like its able to connect to the peer, but the metadata is wrong (# of files is incorrect) and no content data is transferred.

**Comment by karissa** [comment] 2016-11-21 22:00
It seems like this bug probably comes from these lines:

https://github.com/datproject/dat-desktop/blob/master/models/app.js#L58-L69

It might be closing the dat before it finishes importing the files, perhaps.

A better pattern would be to save that dat in a global list of  `archives` in the choo model, and then update this line so the `live-stream.js` doesnt try to re-open the dat: https://github.com/datproject/dat-desktop/blob/master/lib/live-stream.js#L40

**Comment by clkao** [comment] 2016-11-22 01:23
IIUC, the create effect only creates an empty dat and the livestream code reopens the dat and share from there.  If you reload the app, the dat is actually just opened for sharing (not freshly created this time) and importing, but is still not transmitting to other peers.

**Comment by karissa** [comment] 2016-11-22 01:24
If I try to reshare the dat created using Dat Desktop, with the command line, I get this:

```
Karissas-MacBook-Pro-2:dat-desktop karissa$ dat ~/Downloads/dat/9da68e8a2ac9e7b150ab48cf0d96f772bc75b6503b68fd9a1744e52e04f3a037/
Sharing /Users/karissa/Downloads/dat/9da68e8a2ac9e7b150ab48cf0d96f772bc75b6503b68fd9a1744e52e04f3a037

Share Link: b228f0505dc98aa4006194a68cf9cad7c0440039803147b277c974576fe2e6f9
The Share Link is secret and only those you share it with will be able to get the files

[                             ] Sharing 0 files (0 B)

Waiting for connections.
``

**Comment by karissa** [comment] 2016-11-22 01:25
Ah I see what is going on here. I think that the livestream code assumes its a download and isn't using the local path.

**Comment by karissa** [comment] 2016-11-22 02:33
nevermind, its creating a path in Downloads but doesnt use it

**Comment by juliangruber** [comment] 2016-11-22 12:13
Alright, I'll try to come up with a PR that doesn't rely on any `.close()` implementation for now

**Comment by juliangruber** [comment] 2016-11-22 12:18
So instead of the live stream, it will use one initial read stream to load archives and then on archive create add the archive to the model and persist it in the db.

**Comment by juliangruber** [comment] 2016-11-22 12:20
This line seems to be breaking currently, as `root === undefined`: https://github.com/datproject/dat-desktop/blob/master/lib/live-stream.js#L41

Will be fixed by my PR too.

**Comment by karissa** [comment] 2016-11-22 20:08
awesome, thanks julian!

**Comment by Kriesse** [comment] 2016-12-06 13:27
Appears to be fixed? Can we close? @juliangruber

**Comment by juliangruber** [comment] 2016-12-06 15:59
yes, fixed by the live stream refactor :)

**Closed by juliangruber** 2016-12-06 15:59 UTC
