### ISSUE TITLE
Issues with dat-desktop 1.0.3

### ISSUE THREAD

**Issue by beingalink** [datproject/dat-desktop#294] opened 2017-03-08 21:30 UTC
- [ ] Upload speed indicator doesn't work (always 0 even when uploading)

- [x] When closing dat-desktop and re-opening all dats in the list are lost (intended?) (https://github.com/datproject/dat-desktop/commit/3aab73c3a2d110972dff222914f054babb52f8f5)

- [ ] the peer count is sometimes off

- [x] there's no import progress bar (sleep landed)

EDIT: modified by @juliangruber

**Comment by yoshuawuyts** [comment] 2017-03-13 11:03
@beingalink thanks for reporting! :sparkles:

**Comment by juliangruber** [comment] 2017-03-16 19:01
> Upload speed indicator doesn't work (always 0 even when uploading)

I can't reproduce. Is this on OSX? I verified by also running local dat cli and it showed upload speed in desktop.

**Comment by juliangruber** [comment] 2017-03-16 19:01
> the peer count is sometimes off

Do you have a way to reproduce?

**Comment by juliangruber** [comment] 2017-03-16 19:04
> there's no import progress bar

we said in https://github.com/datproject/dat-desktop/issues/166#issuecomment-278951440 that we can omit this for now, do you think we should make it a priority again?

I agree btw that it would be nice to reflect that. Maybe the progress bar should have two phases?

**Comment by karissa** [comment] 2017-03-16 19:10
How large was the dat you were trying to upload? Perhaps it takes a few seconds for the upload indicator to activate.

**Comment by beingalink** [comment] 2017-03-16 21:16
![upload speed indicator](https://www.dropbox.com/s/4us3imzg4t63l4v/Screenshot%202017-03-16%2022.12.42.png)

As you can see dat-cli is downloading but no upload is indiated in dat-desktop. Waiting doesn't change it.

Regarding peer count, I couldn't find a reliable way to reproduce the problem. Will post here if I will find a way.

**Comment by juliangruber** [comment] 2017-05-15 11:28
Since SLEEP landed, I'm closing this for now. I haven't seen any of the aforementioned issues since :)

**Closed by juliangruber** 2017-05-15 11:28 UTC
Labels: Priority: High, Status: Available, Type: Bug
