### ISSUE TITLE
Error when re-creating a Dat

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#210] opened 2017-02-10 17:13 UTC
When I remove a Dat, delete it from disk, and then re-add it again via "import dat" in the app, this happens:

<img width="996" alt="screen shot 2017-02-10 at 6 10 38 pm" src="https://cloud.githubusercontent.com/assets/53684/22836353/5041e1fc-efbc-11e6-83b5-6f55748c8a3d.png">

When I refresh the app, it works. We sometimes get random DB.Lock errors; @joehand any ideas what we can do for this?

**Comment by joehand** [comment] 2017-02-10 18:04
Something in a recent hyperdrive/hypercore update made it so `dat.close` is not working. 

Tracking that issue in dat-node https://github.com/datproject/dat-node/issues/98

**Comment by yoshuawuyts** [comment] 2017-02-10 18:29
@joehand Ooph, rough. We're thinking of adding a lil UI thing to restart the app from the drop down menu if needed. Would be cool if this could be somewhat high on the priority list tho; would def be helpful for when we push this into the public.

**Comment by joehand** [comment] 2017-02-10 18:57
Definitely high priority! I think its related (or at least started) with the replication problems https://github.com/datproject/dat/issues/635. 

Tried some quick fixes yesterday but didn't get anything working. I'm hoping it fixes itself when we fix these replication issues, if not its next on the list.

**Comment by yoshuawuyts** [comment] 2017-02-20 13:39
@joehand assigned you for now because it's blocked on https://github.com/datproject/dat/issues/635 - when it's resolved / have anything to test could you let us know here? Thanks! :sparkles:

**Comment by joehand** [comment] 2017-02-20 18:01
This should be fixed with https://github.com/mafintosh/hyperdrive/pull/127, hyperdrive version `7.14.3`. Tried to reproduce with fresh node_modules and was not able to.

**Closed by joehand** 2017-02-20 18:01 UTC
Labels: Priority: Critical, Status: Blocked, Type: Bug
