### ISSUE TITLE
Create New Dat via Drag and Drop does not work

### ISSUE THREAD

**Issue by Kriesse** [datproject/dat-desktop#85] opened 2016-11-21 06:10 UTC
When attempting to drag a file or folder onto the Desktop app, instead of creating a dat, it behaves like a browser (either prompts to save the file or displays the folder).

**Comment by juliangruber** [comment] 2016-11-21 18:13
oh, dang! Yeah, so it should _not_ accept dropping a file, only folders are supported by dat.

**Comment by yoshuawuyts** [comment] 2016-11-21 18:24
This doesn't seem to be a limitation by hyperdrive tho, right? From the
example code it seemed like random access file could write to any file
location

**Comment by juliangruber** [comment] 2016-11-21 18:32
@yoshuawuyts when we used `hyper*` directly, we could support this mode, however `dat-js` currently doesn't plan to support it as `dat(1)` also won't.

**Comment by yoshuawuyts** [comment] 2016-11-21 19:13
Oh, do you mean by `dat(1)` not supporting it that it doesn't right now -
or that a conscious decision has been made to never support it? - in the
latter case I'd be disappointed as sharing single files seems like a very
useful thing to do.

**Comment by karissa** [comment] 2016-11-21 20:15
We are trying to compete with dropbox here which is folder based, and want to add collaborators to collaborate. 

I'm down with adding single file support at some point in the future, but how do you feel about tabling it until we get folders to work well?

**Comment by Kriesse** [comment] 2016-12-06 23:51
Quick solution for now: Disable drag and drop /cc @yoshuawuyts

**Comment by juliangruber** [comment] 2016-12-14 11:06
I'll try to make dat desktop a drop target for folders only. If this doesn't work, I'll disable drag and drop completely.

**Comment by juliangruber** [comment] 2016-12-14 11:40
will be fixed by https://github.com/datproject/dat-desktop/pull/113

**Comment by karissa** [comment] 2017-01-26 21:51
Broken again :(

**Comment by juliangruber** [comment] 2017-01-30 13:54
@karissa i can't reproduce, dropping a folder works for me. can you post a screen cap or stack trace?

**Comment by juliangruber** [comment] 2017-02-09 10:51
bump

**Comment by Kriesse** [comment] 2017-02-10 18:22
Tested the latest build on my and @yoshuawuyts machines:
- drag and drop a folder to create new dat: works ✅
- drag and drop a single file: does not work – but i believe that is expected?

@karissa: Can you still reproduce?

**Comment by karissa** [comment] 2017-02-10 18:41
Great, letscall it fixed! Yeah we are still doing only folders because we are trying to be feature parity with the cli

**Closed by karissa** 2017-02-10 18:41 UTC
Labels: bug
